#include <platform.h>


/*****************************************************************************************************************************************
 * NOTE: Exception Model
 * 
 * Exception States:
 * 1. Inactive
 * 2. Pending
 * 3. Active
 * 4. Active and Pending
 * 
 * Inactive:
 * 1. The exception is not active or pending
 * 
 * Pending:
 * 1. The exception is waiting to be serviced by the processor.
 * 2. An interrupt request from a peripheral or from software can change the state of the corresponding interrupt to pending.
 * 
 * Active:
 * 1. An exception that is being serviced by the processor but has not completed.
 * 2. An exception handler can interrupt the execution of another exception handler. In this case both exceptions are in the active state.
 * 
 * Active and Pending:
 * 1. The exception is being serviced by the processor and there is a pending exception from the same source.
 * 
 * NOTE: Exception Types
 * 1. Reset              2. NMI
 * 3. HardFault          4. MemManage
 * 5. BusFault           6. UsageFault
 * 7. SVC call           8. PendSV
 * 9. SysTick            10. Interrupt (IRQ)
 * 
 * 1. Reset
 * Reset is invoked on power up or a warm reset. The exception model treats reset as a special form of exception. When reset is asserted,
 * the operation of the processor stops, potentially at any point in an instruction. When reset is deasserted, execution restarts from the
 * address provided by the reset entry in the vector table. Execution restarts as privileged execution in Thread mode.
 * 
 * 2. NMI
 * A NonMaskable Interrupt (NMI) can be signalled by a peripheral or triggered by software. This is the highest priority exception other than 
 * reset. It is permanently enabled and has a fixed priority of -2. NMIs cannot be
 * a. masked or prevented from activation by any other exception
 * b. preempted by any exception other than Reset
 * 
 * 3. HardFault
 * A HardFault is an exception that occurs because of an error during exception processing, or because an exception cannot be managed by
 * any other exception mechanism. HardFaults have a fixed priority of -1, meaning they have higher priority than any exception with
 * configurable priority
 * 
 * 4. MemManage
 * A MemManage fault is an exception that occurs because of a memory protection related fault. The MPU or the fixed memory protection 
 * constraints determines this fault, for both instruction and data memory transactions. This fault is always used to abort instruction
 * accesses to Execute Never (XN) memory regions
 * 
 * 5. BusFault
 * A BusFault is an exception that occurs because of a memory related fault for an instruction or data memory transaction. This might be from
 * an error detected on a bus in the memory system
 * 
 * 6. UsageFault
 * A UsageFault is an exception that occurs because of a fault related to instruction execution. This includes
 * 1. an undefined instruction
 * 2. an illegal unaligned access
 * 3. invalid state on instruction execution
 * 4. an error on exception return.
 * 
 * The following can cause a UsageFault when the core is configured to report them
 * 1. an unaligned address on word and halfword memory access
 * 2. division by zero.
 * 
 * 7. SVCall:
 * A supervisor call (SVC) is an exception that is triggered by the SVC instruction. In an OS environment, applications can use SVC
 * instructions to access OS kernel functions and device drivers 
 *
 * 8. PendSV:
 * PendSV is an interrupt-driven request for system-level service. In an OS environment, use PendSV for context switching when no other
 * exception is active
 * 
 * 9. SysTick:
 * A SysTick exception is an exception the system timer generates when it reaches zero. Software can also generate a SysTick exception. In an
 * OS environment, the processor can use this exception as system tick
 * 
 * 10. Interrupt (IRQ)
 * A interrupt, or IRQ, is an exception signalled by a peripheral, or generated by a software request. All interrupts are asynchronous to
 * instruction execution. In the system, peripherals use interrupts to communicate with the processor.
 * 
 * NOTE: Refer exception1 image for exception table
 * 1. For an asynchronous exception, other than reset, the processor can execute another instruction between when the exception is
 *    triggered and when the processor enters the exception handler
 * 2. Privileged software can disable the exceptions shown in exception1 image, having configurable priority
 *    Refer below section in Cortex-M3 manual for the same
 *    a. System Handler Control and State Register
 *    b. Interrupt Clear-enable Registers
 * 
 * Exception Handlers: The processor handles exception using
 * 
 * Interrupt Service Routine:
 * The IRQ interrupts are the exceptions handled by ISRs
 * 
 * Fault Handlers:
 * HardFault, MemManage fault, UsageFault, and BusFault are fault exceptions handled by the fault handlers.
 * 
 * System Handlers:
 * NMI, PendSV, SVCall SysTick, and the fault exceptions are all system exceptions that are handled by system handlers.
 * 
 * NOTE: Vector Table
 *****************************************************************************************************************************************/
